baseURL = "https://stew.reclaim.hosting/"
languageCode = "en-us"
title = "History of Papyrology"
theme = "Tale"
toc = true
paginate = 10000
sectionPagesMenu = "main"
[taxonomies]
  category = 'categories'
  sources = "source"
  name = "people"
  place = "places"
  orgs = "organizations"
  rs = "references"
  tag = 'tags'
  [[related.indices]]
  name = 'people'
  weight = 100
  [[related.indices]]
  name = 'source'
  weight = 100
  
[menu]
[[menu.main]]
  name = 'About'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -110
[[menu.main]]
  name = 'People'
  post = "<span class='alert'></span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/people/'
  weight = -100
[[menu.main]]
  name = 'Places'
  post = "<span class='alert'></span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/places/'
  weight = -100
[[menu.main]]
  name = 'Organizations'
  post = "<span class='alert'></span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/organizations/'
  weight = -100
[[menu.main]]
  name = 'References'
  post = "<span class='alert'></span>"
  pre = "<i class='fa fa-road'></i>"
  url = '/references/'
  weight = -100
